<%--  emxInfoVisiblePageInclude.inc

   Copyright (c) 2016 Dassault Systemes. All rights reserved.
   This program contains proprietary and trade secret information of
   Dassault Systemes and its subsidiaries. Copyright notice is precautionary only
   and does not evidence any actual or intended publication of such program

--%>
<%--  


   static const char RCSID[] = $Id: emxInfoVisiblePageInclude.inc
--%>


<%--@include file = "emxDesignStyle.jsp"--%>
<%@include file = "emxMQLNotice.inc"%>


<%
request.setAttribute("MQLNoticeFlag", "true");
%>
